### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by mtehver**
* Define few missing variables (there are still some left)
* Fix missing rivers (when defined as linestrings)
* Fix a typo (replacxe -> replace)

### CODE REVIEW

**Comment by farfromrefug** [comment]
Thanks i actually just fixed those locally thanks to your new error reporting :D
EDIT: cant get the `when` to work :P. Can you share an example ... :D :D

**Comment by mtehver** [comment]
@farfromrefug Regarding `when`, you can basically use any expression for filtering. For example:

```
when ([id] = [nuti::selection_id]) {
  line-color: #f00;
}
```
But compared to `[FIELD OP VALUE]` filters that have limited form, `when` filtering is much more expensive and various optimizations are not applied to it. So use with caution.

**Comment by farfromrefug** [comment]
@mtehver thanks for the explanation. It works perfectly!
And yes is use carefully in a local geojson layer with 0-100 features at most. It is dead fast.
Btw: does that when rule exists in mapknik ? I am asking because i am looking closely at geostyler which could allow to translate from cartocss(mapknik) to mapbox.

**Comment by mtehver** [comment]
@farfromrefug If you use simple conditions in `when`  conditions, then it should be fully compatible with Mapnik. So my guess is that the following expression should work just fine:

```
when ([class] = 'road' && ([subclass] = 'minor' || [subclass] = 'major')) {
  ...
}
```

Not sure about GeoStyler, never tried it.

**Pull request merged**
